# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Miguel Tavares
tagline:          'developer journal'
description:      'developer journal'
url:              http://migueltavar.es
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Miguel Tavares'
  url:            https://twitter.com/buzzmeekz

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
github:
  repo:             https://github.com/buzzmeekz
disqus:
  shortname:        migueltavares
google_analytics:   UA-105707495-1